count_right_multi: 0
count_right_single: 3
count_wrong_multi: 11
count_wrong_single: 3
current_multi: 11
current_single: 6
right_id_list_multi: []
right_id_list_single:
- 0
- 3
- 5
wrong_id_list_multi:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
wrong_id_list_single:
- 1
- 2
- 4
